---
commonAttributes:
  - allowNull: false
    dataTypeKey: long
    name: createUser
  - allowNull: false
    dataTypeKey: date
    defaultValue: getdate()
    name: createDate
  - allowNull: false
    dataTypeKey: long
    name: editUser
  - allowNull: false
    dataTypeKey: date
    defaultValue: getdate()
    name: editDate
  - allowNull: false
    dataTypeKey: long
    defaultValue: 0
    name: version
  - allowNull: false
    dataTypeKey: boolean
    defaultValue: 0
    name: phantom
  - allowNull: false
    dataTypeKey: boolean
    defaultValue: 0
    name: deleted
commonTemplateNames:
  - result
  - filter
  - sorter
  - ajaxresponse
  - basedao
dataGenerator:
  randomDate:
    from: 2023-05-01T00:00:00.000Z
    to: 2023-10-30T00:00:00.000Z
  randomFloat:
    from: 0
    to: 100
  randomInt:
    from: 0
    to: 100
  randomString:
    maxLength: 100
    minLength: 0
entities:
  - attributes:
      - allowNull: false
        autoId: true
        dataTypeKey: long
        name: id
        primaryKey: true
      - allowNull: false
        dataTypeKey: string
        name: firstName
        searchable: true
        size: 50
      - allowNull: true
        dataTypeKey: string
        name: lastName
        searchable: true
        size: -1
    disableCommonAttributes: false
    enableAdd: true
    enableDelete: true
    enableList: true
    enableUpdate: true
    generateHistoryEntity: true
    index:
      - attributeNames:
          - firstName
          - lastName
        name: MusicianIndex
        unique: true
    name: musician
    templateNames:
      - table
      - constraint
      - index
      - procedure
      - ajaxcontroller
      - jscontroller
      - dto
      - service
      - impl
      - dao
  - attributes:
      - allowNull: false
        autoId: true
        dataTypeKey: long
        name: id
        primaryKey: true
      - allowNull: false
        dataTypeKey: string
        name: name
        searchable: true
        size: 40
    disableCommonAttributes: true
    enableAdd: true
    enableDelete: true
    enableList: true
    enableUpdate: true
    generateHistoryEntity: true
    name: band
    templateNames:
      - table
      - constraint
      - index
      - procedure
      - ajaxcontroller
      - dto
      - impl
      - service
      - dao
  - attributes:
      - allowNull: false
        dataTypeKey: long
        name: musicianId
        primaryKey: true
        refAttributeName: id
        refEntityName: musician
      - allowNull: false
        dataTypeKey: long
        name: bandId
        primaryKey: true
        refAttributeName: id
        refEntityName: band
    disableCommonAttributes: true
    enableAdd: true
    enableDelete: true
    enableList: true
    enableUpdate: true
    generateHistoryEntity: true
    name: bandmember
    templateNames:
      - table
      - procedure
      - constraint
      - index
      - ajaxcontroller
      - dto
      - impl
      - service
      - dao
metaData:
  java:
    attributeSeparator: ','
    baseNameSpace: de.drazil.ptahtest.generated
    dataTypes:
      boolean:
        dataType: Boolean
        nonNullDataType: boolean
      date:
        dataType: java.util.Date
        nonNullDataType: java.util.Date
      double:
        dataType: Double
        nonNullDataType: double
      int:
        dataType: Integer
        nonNullDataType: int
      long:
        dataType: Long
        nonNullDataType: long
      string:
        dataType: String
        hasSize: true
        nonNullDataType: String
    enableMultiAttributeIdOption: true
    fileSuffix: java
    outputPath: src/main/java_generated/
    templatePath: java/
    writeSeparateFile: true
  js:
    attributeSeparator: ','
    dataTypes:
      boolean:
        dataType: null
        nonNullDataType: null
      date:
        dataType: null
        nonNullDataType: null
      double:
        dataType: null
        nonNullDataType: null
      int:
        dataType: null
        nonNullDataType: null
      long:
        dataType: null
        nonNullDataType: null
      string:
        dataType: null
        nonNullDataType: null
    enableMultiAttributeIdOption: true
    fileSuffix: js
    outputPath: src/main/resources_generated/static/js/
    templatePath: js/
    writeSeparateFile: true
  sql:
    attributeSeparator: ','
    dataTypes:
      boolean:
        dataType: bit
        hasSize: false
        nonNullDataType: bit
      date:
        dataType: date
        hasSize: false
        nonNullDataType: date
      long:
        dataType: bigint
        hasSize: false
        nonNullDataType: bigint
      string:
        dataType: nvarchar
        hasSize: true
        maxSize: MAX
        nonNullDataType: nvarchar
    fileSuffix: sql
    outputPath: src/main/resources_generated/dbscripts/
    templatePath: database/mssql/
    templateProcessingOrder:
      - table
      - view
      - procedure
      - constraint
      - index
    writeSeparateFile: false
templateDefinition:
  ajaxcontroller:
    metaData: java
    namePattern: '%sController'
    nameSpace: controller
  ajaxresponse:
    metaData: java
    namePattern: AjaxResponse
    nameSpace: model
  basedao:
    metaData: java
    namePattern: BaseDAO
    nameSpace: service.dao
  constraint:
    metaData: sql
    namePattern: '%s'
    nameSpace: dbo
  dao:
    metaData: java
    namePattern: '%sDAO'
    nameSpace: service.dao
  dto:
    metaData: java
    namePattern: '%sDTO'
    nameSpace: dto
  filter:
    metaData: java
    namePattern: Filter
    nameSpace: model
  formcontroller:
    metaData: java
    namePattern: '%sController'
    nameSpace: controller
  id:
    metaData: java
    namePattern: '%sId'
    nameSpace: dto
  impl:
    metaData: java
    namePattern: '%sServiceImpl'
    nameSpace: service.impl
  index:
    metaData: sql
    namePattern: '%s'
    nameSpace: dbo
  jscontroller:
    metaData: js
    namePattern: '%sController'
    nameSpace: controller
  procedure:
    metaData: sql
    namePattern: Handle%s
    nameSpace: dbo
  result:
    metaData: java
    namePattern: Result
    nameSpace: model
  service:
    metaData: java
    namePattern: I%sService
    nameSpace: service
  sorter:
    metaData: java
    namePattern: Sorter
    nameSpace: model
  table:
    metaData: sql
    namePattern: '%s'
    nameSpace: dbo
  view:
    metaData: sql
    namePattern: '%sView'
    nameSpace: dbo
virtualEntities:
  - attributes:
      - allowNull: false
        autoId: true
        dataTypeKey: long
        name: id
        primaryKey: true
      - allowNull: false
        dataTypeKey: string
        name: firstName
        size: 50
      - allowNull: true
        dataTypeKey: string
        name: lastName
        size: -1
    name: musicianoverview
    source: |-
      select * from table 
      where x=1
      and y=2
    sourceType: text
    templateNames:
      - view